"""Added cover image

Revision ID: da0b160016b3
Revises: 
Create Date: 2025-11-25 10:42:37.946638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da0b160016b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_logs')
    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.alter_column('added_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('book_copies_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['book_id'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=150), nullable=False))
        batch_op.alter_column('total_copies',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('available_copies',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('added_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.alter_column('fine_amount',
               existing_type=mysql.DECIMAL(precision=7, scale=2),
               type_=sa.Float(),
               nullable=True,
               existing_server_default=sa.text("'0.00'"))
        batch_op.drop_constraint(batch_op.f('borrowed_books_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('borrowed_books_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'book_copies', ['copy_id'], ['copy_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_position', sa.Integer(), nullable=False))
        batch_op.alter_column('reservation_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('reservations_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reservations_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['book_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('review_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('reviews_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reviews_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['book_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_ibfk_2'), 'books', ['book_id'], ['book_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('reviews_ibfk_1'), 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('review_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rating',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reservations_ibfk_2'), 'books', ['book_id'], ['book_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('reservations_ibfk_1'), 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('reservation_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('queue_position')

    with op.batch_alter_table('borrowed_books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('borrowed_books_ibfk_2'), 'book_copies', ['copy_id'], ['copy_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('borrowed_books_ibfk_1'), 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('fine_amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=7, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0.00'"))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('added_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('available_copies',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_copies',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('cover_image')

    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('book_copies_ibfk_1'), 'books', ['book_id'], ['book_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('added_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('system_logs',
    sa.Column('log_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('system_logs_ibfk_1'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
